### ISSUE TITLE
Build error.

### ISSUE THREAD

**Issue by ashoksoni** [Koenkk/proprietary_vendor_oneplus#1]
Hi, 

I am getting this error while building with this repo.

vendor/oneplus/oneplus3: MODULE.TARGET.SHARED_LIBRARIES.libril already defined by hardware/ril-caf/libril.

Same repo ending with _old works fine. Can you suggest me what do I need to change to fix this?

Thanks.

**Comment by ujwalp15** [comment]
its fixed in my trees, I've fixed wifi issues too
https://github.com/ujwalp15/android_device_oneplus_oneplus3/commits/oct-14.1-test
